/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ffos.view;

import com.github.javafaker.Faker;
import ffos.controller.ObradaMjesto;
import ffos.controller.ObradaOsoba;
import ffos.controller.ObradaRacunalo;

/**
 *
 * @author Marija
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMjesta = new javax.swing.JButton();
        btnRacunala = new javax.swing.JButton();
        btnOsobe = new javax.swing.JButton();
        btnDodajMjesta = new javax.swing.JButton();
        btnDodajRacunala = new javax.swing.JButton();
        btnDodajOsobe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMjesta.setText("Mjesta");
        btnMjesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMjestaActionPerformed(evt);
            }
        });

        btnRacunala.setText("Računala");
        btnRacunala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacunalaActionPerformed(evt);
            }
        });

        btnOsobe.setText("Osobe");
        btnOsobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsobeActionPerformed(evt);
            }
        });

        btnDodajMjesta.setText("Dodaj Mjesta");
        btnDodajMjesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajMjestaActionPerformed(evt);
            }
        });

        btnDodajRacunala.setText("Dodaj Računala");
        btnDodajRacunala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajRacunalaActionPerformed(evt);
            }
        });

        btnDodajOsobe.setText("Dodaj Osobe");
        btnDodajOsobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajOsobeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMjesta)
                    .addComponent(btnRacunala)
                    .addComponent(btnOsobe))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodajOsobe)
                    .addComponent(btnDodajRacunala)
                    .addComponent(btnDodajMjesta))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMjesta)
                    .addComponent(btnDodajMjesta))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRacunala)
                    .addComponent(btnDodajRacunala))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOsobe)
                    .addComponent(btnDodajOsobe))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMjestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMjestaActionPerformed
        new FormaMjesto().setVisible(true);
    }//GEN-LAST:event_btnMjestaActionPerformed

    private void btnRacunalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacunalaActionPerformed
        new FormaRacunalo().setVisible(true);
    }//GEN-LAST:event_btnRacunalaActionPerformed

    private void btnOsobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsobeActionPerformed
        new FormaOsoba().setVisible(true);
    }//GEN-LAST:event_btnOsobeActionPerformed

    private void btnDodajMjestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajMjestaActionPerformed
        ObradaMjesto om = new ObradaMjesto();
        Faker faker = new Faker();
        
        for(int i=0;i<10;i++){
            om.setNew();
            om.setPodaci(faker.ancient().god());
            try {
                om.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDodajMjestaActionPerformed

    private void btnDodajRacunalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajRacunalaActionPerformed
        ObradaRacunalo or = new ObradaRacunalo();
        Faker faker = new Faker();
        
        for(int i=0;i<20;i++){
            or.setNew();
            or.setPodaci(faker.book().title(), faker.company().name());
            try {
                or.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDodajRacunalaActionPerformed

    private void btnDodajOsobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajOsobeActionPerformed
        ObradaOsoba oo = new ObradaOsoba();
        Faker faker = new Faker();
        
        for(int i=0;i<15;i++){
            oo.setNew();
            oo.setPodaci("Ana", "Anić", null, null);
            try {
                oo.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDodajOsobeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajMjesta;
    private javax.swing.JButton btnDodajOsobe;
    private javax.swing.JButton btnDodajRacunala;
    private javax.swing.JButton btnMjesta;
    private javax.swing.JButton btnOsobe;
    private javax.swing.JButton btnRacunala;
    // End of variables declaration//GEN-END:variables
}
