/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ffos.mmilosevic_kol2.view;

import ffos.mmilosevic_kol2.controller.ObradaOsoba;
import ffos.mmilosevic_kol2.controller.ObradaRekreacija;
import ffos.mmilosevic_kol2.controller.ObradaSport;
import ffos.mmilosevic_kol2.model.Osoba;
import ffos.mmilosevic_kol2.model.Rekreacija;
import ffos.mmilosevic_kol2.model.Sport;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marija
 */
public class FormaRekreacija extends javax.swing.JFrame implements ViewAktivnosti{
    
    private ObradaRekreacija obrada;

    /**
     * Creates new form FormaRekreacija
     */
    public FormaRekreacija() {
        initComponents();
        
        obrada = new ObradaRekreacija();
        ucitajPodatke();
        
        DefaultComboBoxModel<Sport> m = new DefaultComboBoxModel<>();
        m.addAll(new ObradaSport().read());
        cmbSport.setModel(m);
        cmbSport.repaint();
        
        DefaultListModel<Osoba> mr = new DefaultListModel<>();
        mr.addAll(new ObradaOsoba().read());
        lstOsobeUBazi.setModel(mr);
        lstOsobeUBazi.repaint();
        
        lstOsobaRekreacije.setModel(new DefaultListModel<>());
    }
    
        @Override
    public void ucitajPodatke(){
        DefaultListModel<Rekreacija> r = new DefaultListModel<>();
        r.addAll(obrada.read());
        lstEntiteti.setModel(r);
        lstEntiteti.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEntiteti = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        cmbSport = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstOsobaRekreacije = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstOsobeUBazi = new javax.swing.JList<>();
        DodajOsobu = new javax.swing.JButton();
        makniOsobu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstEntiteti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntitetiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEntiteti);

        jLabel1.setText("Naziv");

        jLabel2.setText("Sport");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstOsobaRekreacije);

        jLabel3.setText("Osoba rekreacije");

        jLabel4.setText("Osoba u bazi");

        jScrollPane3.setViewportView(lstOsobeUBazi);

        DodajOsobu.setText("<");
        DodajOsobu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajOsobuActionPerformed(evt);
            }
        });

        makniOsobu.setText(">");
        makniOsobu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makniOsobuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(cmbSport, 0, 135, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(txtNaziv)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addComponent(btnCreate)
                            .addComponent(btnUpdate))))
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DodajOsobu)
                            .addComponent(makniOsobu))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel1)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnCreate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete))
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(DodajOsobu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(makniOsobu)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        obrada.setNew();
        List<Osoba> osobe = new ArrayList<>();
        DefaultListModel<Osoba> o = (DefaultListModel<Osoba>) lstOsobaRekreacije.getModel();
        for(int i=0;i<o.size();i++){
            osobe.add(o.get(i));
        }        
        
        obrada.setPodaci(txtNaziv.getText(), (Sport)cmbSport.getSelectedItem(), osobe);

        try {
            obrada.create();
            ucitajPodatke();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(lstEntiteti.getSelectedValue()==null){
            return;
        }
        var e = lstEntiteti.getSelectedValue();
        obrada.setEntitet(e);
        
        List<Osoba> osobe = new ArrayList<>();
        DefaultListModel<Osoba> m = (DefaultListModel<Osoba>) lstOsobaRekreacije.getModel();
        for(int i=0;i<m.size();i++){
            osobe.add(m.get(i));
        }
        
        obrada.setPodaci(txtNaziv.getText(), (Sport)cmbSport.getSelectedItem(), osobe);
        try {
            obrada.update();
            ucitajPodatke();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(lstEntiteti.getSelectedValue() == null){
            return;
        }
        obrada.setEntitet(lstEntiteti.getSelectedValue());
        try {
            obrada.delete();
            ucitajPodatke();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void DodajOsobuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajOsobuActionPerformed
        if(lstOsobeUBazi.getSelectedValue() == null){
            return;
        }
        ((DefaultListModel<Osoba>)lstOsobaRekreacije.getModel()).addElement(lstOsobeUBazi.getSelectedValue());
        lstOsobaRekreacije.repaint();
    }//GEN-LAST:event_DodajOsobuActionPerformed

    private void makniOsobuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makniOsobuActionPerformed
        if(lstOsobaRekreacije.getSelectedValue()==null){
            return;
        }
        
        ((DefaultListModel<Osoba>)lstOsobaRekreacije.getModel()).removeElement(lstOsobaRekreacije.getSelectedValue());
        lstOsobaRekreacije.repaint();
    }//GEN-LAST:event_makniOsobuActionPerformed

    private void lstEntitetiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntitetiValueChanged
        if(evt.getValueIsAdjusting() || lstEntiteti.getSelectedValue() == null){
            return;
        }
        txtNaziv.setText(lstEntiteti.getSelectedValue().getNaziv());
        cmbSport.setSelectedItem(lstEntiteti.getSelectedValue().getSport());
        DefaultListModel<Osoba> m = new DefaultListModel<>();
        m.addAll(lstEntiteti.getSelectedValue().getOsobe());
        lstOsobaRekreacije.setModel(m);
        lstOsobaRekreacije.repaint();
    }//GEN-LAST:event_lstEntitetiValueChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DodajOsobu;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Sport> cmbSport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Rekreacija> lstEntiteti;
    private javax.swing.JList<Osoba> lstOsobaRekreacije;
    private javax.swing.JList<Osoba> lstOsobeUBazi;
    private javax.swing.JButton makniOsobu;
    private javax.swing.JTextField txtNaziv;
    // End of variables declaration//GEN-END:variables
}
