/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ffos.mmilosevic_kol2.view;

import com.github.javafaker.Faker;
import ffos.mmilosevic_kol2.controller.ObradaOsoba;
import ffos.mmilosevic_kol2.controller.ObradaRekreacija;
import ffos.mmilosevic_kol2.controller.ObradaSport;
import ffos.mmilosevic_kol2.model.Rekreacija;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marija
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUnosOsoba = new javax.swing.JButton();
        btnUnosSport = new javax.swing.JButton();
        btnUnosRekreacijaOsoba = new javax.swing.JButton();
        btnCrudOsoba = new javax.swing.JButton();
        btnCrudRekreacija = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUnosOsoba.setText("3.1.");
        btnUnosOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosOsobaActionPerformed(evt);
            }
        });

        btnUnosSport.setText("3.2.");
        btnUnosSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosSportActionPerformed(evt);
            }
        });

        btnUnosRekreacijaOsoba.setText("3.4.");
        btnUnosRekreacijaOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosRekreacijaOsobaActionPerformed(evt);
            }
        });

        btnCrudOsoba.setText("3.5.");
        btnCrudOsoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudOsobaActionPerformed(evt);
            }
        });

        btnCrudRekreacija.setText("3.6.");
        btnCrudRekreacija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudRekreacijaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUnosRekreacijaOsoba)
                    .addComponent(btnUnosSport)
                    .addComponent(btnUnosOsoba))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrudRekreacija)
                    .addComponent(btnCrudOsoba))
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnUnosOsoba)
                .addGap(3, 3, 3)
                .addComponent(btnCrudOsoba)
                .addGap(9, 9, 9)
                .addComponent(btnUnosSport)
                .addGap(8, 8, 8)
                .addComponent(btnCrudRekreacija)
                .addGap(9, 9, 9)
                .addComponent(btnUnosRekreacijaOsoba)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrudOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudOsobaActionPerformed
        new FormaOsoba().setVisible(true);
    }//GEN-LAST:event_btnCrudOsobaActionPerformed

    private void btnCrudRekreacijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudRekreacijaActionPerformed
        new FormaRekreacija().setVisible(true);
    }//GEN-LAST:event_btnCrudRekreacijaActionPerformed

    private void btnUnosOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosOsobaActionPerformed
        ObradaOsoba oo = new ObradaOsoba();
        Faker faker = new Faker();
        
        for(int i=0;i<20;i++){
            oo.setNew();
            oo.setPodaci("03-05-2006", faker.name().firstName(), faker.name().lastName());
            try {
                oo.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUnosOsobaActionPerformed

    private void btnUnosSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosSportActionPerformed
        ObradaSport os = new ObradaSport();
        Faker faker = new Faker();
        
        for(int i=0;i<120;i++){
            os.setNew();
            os.setPodaci(faker.animal().name(), faker.app().name());
            try {
                os.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUnosSportActionPerformed

    private void btnUnosRekreacijaOsobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosRekreacijaOsobaActionPerformed
        ObradaRekreacija or = new ObradaRekreacija();
        for(int i = 0; i < 180; i++){

        Rekreacija rekreacija = new Rekreacija();
        or.setEntitet(rekreacija);
        or.setPodaci("Rekreacija", null, null);

            Random r = new Random();


        int broj= r.nextInt(21)+19; //ovdje pisete razliku između brojeva koje ste dobili + manji broj
        //or.getEntitet().get
        for(int j = 0; j < broj; j++){
            ObradaOsoba oo= new ObradaOsoba();

            int brojOsobe= r.nextInt(oo.read().size());

        or.entitet.getOsobe().add(oo.read().get(brojOsobe));

        }
         try{
                    or.create();
                    or.setEntitet(null);}
                catch (Exception e){System.out.println("greška");}
         or.setEntitet(null);
        }
    }//GEN-LAST:event_btnUnosRekreacijaOsobaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrudOsoba;
    private javax.swing.JButton btnCrudRekreacija;
    private javax.swing.JButton btnUnosOsoba;
    private javax.swing.JButton btnUnosRekreacijaOsoba;
    private javax.swing.JButton btnUnosSport;
    // End of variables declaration//GEN-END:variables
}
